name: TownyMenu
main: net.trilleo.mc.plugins.townymenu.Main
version: ${projectVersion}
api-version: 1.21
author: Trilleo
description: A GUI addon for Towny
depend:
  - Towny

commands:
  townymenu:
    description: Main command for the TownyMenu plugin
    usage: /townymenu <subcommand> [args]
    aliases:
      - tm
